### ISSUE TITLE
Metamask Notify

### ISSUE THREAD

**Issue by Abhishek357** [Shikhar15606/ElectionDapp#122]
Notify on any screen itself about whether the metamask is installed as an extension or not. If not give a clear message.

**Comment by Shikhar15606** [comment]
Currently, if the metamask is not present a very blunt message is displayed. i.e:

"Loading Web3, accounts, and contract..."
Add a nice message screen (with a few screenshots about how to configure metamask) asking the user to install and configure metamask.

**Comment by kirtilodha** [comment]
Hi, can you help with the file of the existing code?

**Comment by Abhishek357** [comment]
> Hi, can you help with the file of the existing code?

here you go @kirtilodha 

https://github.com/Shikhar15606/ElectionDapp/blob/0fd7c0dffcbe30aac1acdc4373657f02c11cac56/client/src/App.js#L76

**Comment by kirtilodha** [comment]
Hii @Abhishek357 I'm unable to run local serve
<img width="617" alt="Capture" src="https://user-images.githubusercontent.com/67586672/146754831-a8e84d3e-c550-468a-b305-4ee7f1e95dc5.PNG">
r
