### ISSUE TITLE
Change Links in README

### ISSUE THREAD

**Issue by Shikhar15606** [Shikhar15606/ElectionDapp#128]
Currently, the images are being fetched from google drive links and sometimes they do not load on the Readme file. So we decided to use Cloudinary to store all the images. I have already uploaded all the images on Cloudinary(which I will share with the one taking up the issue on slack) and we just need to replace the image links with the new ones in the readme file.

Anyone who wants to take up this issue just comment below.

**Comment by Jitulteron7** [comment]
Hi @Shikhar15606  can you assign me on this one

**Comment by Shikhar15606** [comment]
> Hi @Shikhar15606 can you assign me on this one

Ya sure @Jitulteron7. Go ahead
