### ISSUE TITLE
Need to install craco before starting the server

### ISSUE THREAD

**Issue by kirtilodha** [Shikhar15606/ElectionDapp#135]
**Should install craco using "npm install @craco/craco --save"**
<img width="213" alt="Capture" src="https://user-images.githubusercontent.com/67586672/146755939-63f43f28-adfa-4cef-8182-3abc2bd4827b.PNG">

**Comment by kirtilodha** [comment]
@Abhishek357 @Shikhar15606

**Comment by Shikhar15606** [comment]
@kirtilodha I guess that you forgot to run the yarn install command in the client folder. Try installing the dependencies :) If you have any problem in doing that then you may comment below

**Comment by kirtilodha** [comment]
I did yarn install inside the client folder as well, still got this error.

**Comment by Abhishek357** [comment]
> I did yarn install inside the client folder as well, still got this error.


@kirtilodha I hope you are running the `yarn frontend` in the root folder and not in the client?

**Comment by kirtilodha** [comment]
Thanks I got it
